// Code generated by "stringer -type=State -linecomment"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInit-0]
	_ = x[StateStarting-1]
	_ = x[StateRunning-2]
	_ = x[StateStopping-3]
	_ = x[StateStopped-4]
	_ = x[StateCrashed-5]
	_ = x[StateRestarting-6]
}

const _State_name = "InitStartingRunningStoppingStoppedCrashedRestarting"

var _State_index = [...]uint8{0, 4, 12, 19, 27, 34, 41, 51}

func (i State) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_State_index)-1 {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[idx]:_State_index[idx+1]]
}
